# Site wide configuration

title: Advanced Field Botany @ UIdaho
locale: en_US
description: BIOL 460/560 @ the University of Idaho McCall Field Campus
logo: AFB_logo_white.png
search: true
#url: http://localhost:4000
url: http://davetank.github.io/teaching/AFB

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Dave Tank
  avatar: bio-photo-Tank.jpg
  email: dtank@uidaho.edu
  disqus-shortname:
  twitter: dave_tank
  facebook: UIAdvancedFieldBotany
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
